import {
  Users,
  Store,
  FolderTree,
  Package,
  HandshakeIcon,
  ShoppingCart,
  MessageSquare,
  Star,
  Settings,
  type LucideIcon,
} from "lucide-react"

export interface Field {
  name: string
  type: string
  interface?: string
  relationship?: string
  notes?: string
  isPrimaryKey?: boolean
}

export interface Collection {
  id: string
  name: string
  fields: Field[]
}

export interface Module {
  id: string
  name: string
  icon: LucideIcon
  color: string
  collections: Collection[]
}

export interface SchemaData {
  totalCollections: number
  modules: Module[]
}

export const schemaData: SchemaData = {
  totalCollections: 34,
  modules: [
    {
      id: "users",
      name: "User & Profile",
      icon: Users,
      color: "#3b82f6",
      collections: [
        {
          id: "directus_users",
          name: "directus_users (Extended)",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "email", type: "string", notes: "Required, Unique" },
            { name: "password", type: "hash", notes: "Required" },
            { name: "first_name", type: "string" },
            { name: "last_name", type: "string" },
            { name: "avatar", type: "uuid", relationship: "directus_files" },
            { name: "status", type: "string", notes: "active, invited, suspended, archived" },
            { name: "role", type: "uuid", relationship: "directus_roles" },
            { name: "phone", type: "string" },
            { name: "phone_verified", type: "boolean", notes: "Default: false" },
            { name: "email_verified", type: "boolean", notes: "Default: false" },
            { name: "account_type", type: "string", notes: "Required: individual, business" },
            { name: "date_of_birth", type: "date" },
            { name: "gender", type: "string", notes: "male, female, other, prefer_not_to_say" },
            { name: "country", type: "string" },
            { name: "city", type: "string" },
            { name: "address", type: "text" },
            { name: "postal_code", type: "string" },
            { name: "latitude", type: "decimal" },
            { name: "longitude", type: "decimal" },
            { name: "preferred_language", type: "string", notes: "Default: en" },
            { name: "currency", type: "string", notes: "Default: USD" },
            { name: "notification_email", type: "boolean", notes: "Default: true" },
            { name: "notification_push", type: "boolean", notes: "Default: true" },
            { name: "notification_sms", type: "boolean", notes: "Default: false" },
            { name: "is_verified", type: "boolean", notes: "Default: false" },
            { name: "verification_level", type: "integer", notes: "Default: 0 (0-5)" },
            { name: "id_document", type: "uuid", relationship: "directus_files" },
            { name: "id_verified_at", type: "timestamp" },
            { name: "last_login", type: "timestamp" },
            { name: "business_profile", type: "O2M", relationship: "business_profiles" },
            { name: "products", type: "O2M", relationship: "products" },
            { name: "addresses", type: "O2M", relationship: "user_addresses" },
            { name: "favorites", type: "O2M", relationship: "product_favorites" },
            { name: "reviews_given", type: "O2M", relationship: "reviews" },
          ],
        },
        {
          id: "business_profiles",
          name: "business_profiles",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published, archived" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "business_name", type: "string", notes: "Required" },
            { name: "business_name_ar", type: "string", notes: "Arabic" },
            { name: "legal_name", type: "string" },
            { name: "business_type", type: "string", notes: "sole_proprietorship, llc, corporation, partnership" },
            { name: "registration_number", type: "string" },
            { name: "tax_id", type: "string" },
            { name: "business_email", type: "string" },
            { name: "business_phone", type: "string" },
            { name: "website", type: "string" },
            { name: "trade_license", type: "uuid", relationship: "directus_files" },
            { name: "trade_license_expiry", type: "date" },
            { name: "additional_documents", type: "json" },
            { name: "is_verified", type: "boolean", notes: "Default: false" },
            { name: "verified_at", type: "timestamp" },
            { name: "verified_by", type: "uuid", relationship: "directus_users" },
            { name: "verification_notes", type: "text" },
            { name: "can_create_stores", type: "boolean", notes: "Default: true" },
            { name: "max_stores", type: "integer", notes: "Default: 5" },
            { name: "subscription_plan", type: "string", notes: "free, starter, professional, enterprise" },
            { name: "subscription_expires_at", type: "timestamp" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
            { name: "user_created", type: "uuid", relationship: "directus_users", notes: "System" },
            { name: "user_updated", type: "uuid", relationship: "directus_users", notes: "System" },
            { name: "stores", type: "O2M", relationship: "stores" },
          ],
        },
        {
          id: "user_addresses",
          name: "user_addresses",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "label", type: "string", notes: "Home, Work, etc." },
            { name: "is_default", type: "boolean", notes: "Default: false" },
            { name: "address_type", type: "string", notes: "shipping, billing, both" },
            { name: "recipient_name", type: "string" },
            { name: "phone", type: "string" },
            { name: "address_line_1", type: "string", notes: "Required" },
            { name: "address_line_2", type: "string" },
            { name: "city", type: "string", notes: "Required" },
            { name: "state", type: "string" },
            { name: "postal_code", type: "string" },
            { name: "country", type: "string", notes: "Required" },
            { name: "latitude", type: "decimal" },
            { name: "longitude", type: "decimal" },
            { name: "instructions", type: "text", notes: "Delivery instructions" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
          ],
        },
      ],
    },
    {
      id: "stores",
      name: "Stores",
      icon: Store,
      color: "#8b5cf6",
      collections: [
        {
          id: "stores",
          name: "stores",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published, suspended, archived" },
            { name: "sort", type: "integer", notes: "Sortable" },
            { name: "business_profile_id", type: "uuid", relationship: "business_profiles", notes: "Required" },
            { name: "name", type: "string", notes: "Required" },
            { name: "name_ar", type: "string", notes: "Arabic" },
            { name: "slug", type: "string", notes: "Required, Unique" },
            { name: "description", type: "text" },
            { name: "description_ar", type: "text", notes: "Arabic" },
            { name: "logo", type: "uuid", relationship: "directus_files" },
            { name: "cover_image", type: "uuid", relationship: "directus_files" },
            { name: "theme_color", type: "string", notes: "Hex color" },
            { name: "email", type: "string" },
            { name: "phone", type: "string" },
            { name: "whatsapp", type: "string" },
            { name: "country", type: "string" },
            { name: "city", type: "string" },
            { name: "address", type: "text" },
            { name: "postal_code", type: "string" },
            { name: "latitude", type: "decimal" },
            { name: "longitude", type: "decimal" },
            { name: "operating_hours", type: "json" },
            { name: "timezone", type: "string", notes: "Default: UTC" },
            { name: "accepts_swaps", type: "boolean", notes: "Default: true" },
            { name: "accepts_rentals", type: "boolean", notes: "Default: true" },
            { name: "accepts_sales", type: "boolean", notes: "Default: true" },
            { name: "auto_accept_orders", type: "boolean", notes: "Default: false" },
            { name: "minimum_order_amount", type: "decimal" },
            { name: "offers_delivery", type: "boolean", notes: "Default: true" },
            { name: "delivery_zones", type: "json" },
            { name: "delivery_fee", type: "decimal" },
            { name: "free_delivery_threshold", type: "decimal" },
            { name: "total_sales", type: "decimal", notes: "Default: 0, Read-only" },
            { name: "total_orders", type: "integer", notes: "Default: 0, Read-only" },
            { name: "average_rating", type: "decimal", notes: "Default: 0, Read-only" },
            { name: "total_reviews", type: "integer", notes: "Default: 0, Read-only" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
            { name: "products", type: "O2M", relationship: "products" },
            { name: "followers", type: "O2M", relationship: "store_followers" },
            { name: "orders", type: "O2M", relationship: "orders" },
            { name: "seo", type: "O2O", relationship: "seo_metadata" },
          ],
        },
        {
          id: "store_followers",
          name: "store_followers",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "store_id", type: "uuid", relationship: "stores", notes: "Required" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
      ],
    },
    {
      id: "catalog",
      name: "Catalog",
      icon: FolderTree,
      color: "#10b981",
      collections: [
        {
          id: "categories",
          name: "categories",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published, archived" },
            { name: "sort", type: "integer", notes: "Sortable" },
            { name: "parent_id", type: "uuid", relationship: "categories", notes: "Self-referential" },
            { name: "level", type: "integer", notes: "Default: 0" },
            { name: "path", type: "text", notes: "Materialized path" },
            { name: "name", type: "string", notes: "Required" },
            { name: "name_ar", type: "string", notes: "Arabic" },
            { name: "slug", type: "string", notes: "Required, Unique" },
            { name: "description", type: "text" },
            { name: "description_ar", type: "text", notes: "Arabic" },
            { name: "icon", type: "string", notes: "Icon name" },
            { name: "image", type: "uuid", relationship: "directus_files" },
            { name: "cover_image", type: "uuid", relationship: "directus_files" },
            { name: "is_featured", type: "boolean", notes: "Default: false" },
            { name: "allows_swap", type: "boolean", notes: "Default: true" },
            { name: "allows_rent", type: "boolean", notes: "Default: true" },
            { name: "allows_sell", type: "boolean", notes: "Default: true" },
            { name: "products_count", type: "integer", notes: "Default: 0, Read-only" },
            { name: "children", type: "O2M", relationship: "categories" },
            { name: "attributes", type: "O2M", relationship: "category_attributes" },
            { name: "brands", type: "M2M", relationship: "brands" },
            { name: "products", type: "O2M", relationship: "products" },
            { name: "seo", type: "O2O", relationship: "seo_metadata" },
          ],
        },
        {
          id: "category_attributes",
          name: "category_attributes",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published, archived" },
            { name: "sort", type: "integer", notes: "Sortable" },
            { name: "category_id", type: "uuid", relationship: "categories", notes: "Required" },
            { name: "name", type: "string", notes: "Required" },
            { name: "name_ar", type: "string", notes: "Arabic" },
            { name: "slug", type: "string", notes: "Required" },
            {
              name: "attribute_type",
              type: "string",
              notes: "text, number, select, multi_select, boolean, date, color",
            },
            { name: "is_required", type: "boolean", notes: "Default: false" },
            { name: "is_filterable", type: "boolean", notes: "Default: true" },
            { name: "is_searchable", type: "boolean", notes: "Default: true" },
            { name: "options", type: "json", notes: "For select types" },
            { name: "validation_rules", type: "json" },
            { name: "show_in_listing", type: "boolean", notes: "Default: true" },
            { name: "show_in_filters", type: "boolean", notes: "Default: true" },
          ],
        },
        {
          id: "brands",
          name: "brands",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published, archived" },
            { name: "sort", type: "integer", notes: "Sortable" },
            { name: "name", type: "string", notes: "Required" },
            { name: "name_ar", type: "string", notes: "Arabic" },
            { name: "slug", type: "string", notes: "Required, Unique" },
            { name: "description", type: "text" },
            { name: "description_ar", type: "text", notes: "Arabic" },
            { name: "brand_type", type: "string", notes: "Required: local, international" },
            { name: "origin_country", type: "string" },
            { name: "logo", type: "uuid", relationship: "directus_files" },
            { name: "cover_image", type: "uuid", relationship: "directus_files" },
            { name: "is_verified", type: "boolean", notes: "Default: false" },
            { name: "is_official", type: "boolean", notes: "Default: false" },
            { name: "official_account_id", type: "uuid", relationship: "directus_users" },
            { name: "website", type: "string" },
            { name: "support_email", type: "string" },
            { name: "support_phone", type: "string" },
            { name: "is_featured", type: "boolean", notes: "Default: false" },
            { name: "products_count", type: "integer", notes: "Default: 0, Read-only" },
            { name: "followers_count", type: "integer", notes: "Default: 0, Read-only" },
            { name: "models", type: "O2M", relationship: "models" },
            { name: "categories", type: "M2M", relationship: "categories" },
            { name: "followers", type: "O2M", relationship: "brand_followers" },
            { name: "products", type: "O2M", relationship: "products" },
            { name: "representatives", type: "O2M", relationship: "brand_representatives" },
            { name: "seo", type: "O2O", relationship: "seo_metadata" },
          ],
        },
        {
          id: "brand_followers",
          name: "brand_followers",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "brand_id", type: "uuid", relationship: "brands", notes: "Required" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "models",
          name: "models",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published, archived" },
            { name: "sort", type: "integer", notes: "Sortable" },
            { name: "brand_id", type: "uuid", relationship: "brands", notes: "Required" },
            { name: "name", type: "string", notes: "Required" },
            { name: "name_ar", type: "string", notes: "Arabic" },
            { name: "slug", type: "string", notes: "Required" },
            { name: "description", type: "text" },
            { name: "year_released", type: "integer" },
            { name: "image", type: "uuid", relationship: "directus_files" },
            { name: "products", type: "O2M", relationship: "products" },
          ],
        },
        {
          id: "brand_categories",
          name: "brand_categories",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "brand_id", type: "uuid", relationship: "brands", notes: "Required" },
            { name: "category_id", type: "uuid", relationship: "categories", notes: "Required" },
            { name: "is_primary", type: "boolean", notes: "Default: false" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "brand_representatives",
          name: "brand_representatives",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "pending, approved, rejected, revoked" },
            { name: "brand_id", type: "uuid", relationship: "brands", notes: "Required" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "title", type: "string", notes: 'e.g., "Regional Manager"' },
            { name: "permissions", type: "json" },
            { name: "verification_document", type: "uuid", relationship: "directus_files" },
            { name: "verified_at", type: "timestamp" },
            { name: "verified_by", type: "uuid", relationship: "directus_users" },
            { name: "valid_from", type: "timestamp" },
            { name: "valid_until", type: "timestamp" },
          ],
        },
      ],
    },
    {
      id: "products",
      name: "Products",
      icon: Package,
      color: "#f59e0b",
      collections: [
        {
          id: "products",
          name: "products",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            {
              name: "status",
              type: "string",
              notes: "draft, pending_review, published, sold, rented, swapped, archived",
            },
            { name: "sort", type: "integer", notes: "Sortable" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "store_id", type: "uuid", relationship: "stores", notes: "Optional (NULL for individuals)" },
            { name: "category_id", type: "uuid", relationship: "categories", notes: "Required" },
            { name: "subcategory_id", type: "uuid", relationship: "categories", notes: "Optional" },
            { name: "brand_id", type: "uuid", relationship: "brands", notes: "Optional" },
            { name: "model_id", type: "uuid", relationship: "models", notes: "Optional" },
            { name: "title", type: "string", notes: "Required" },
            { name: "title_ar", type: "string", notes: "Arabic" },
            { name: "slug", type: "string", notes: "Required, Unique" },
            { name: "description", type: "text" },
            { name: "description_ar", type: "text", notes: "Arabic" },
            { name: "condition", type: "string", notes: "Required: new, like_new, good, fair, poor" },
            { name: "condition_notes", type: "text" },
            { name: "available_for_sale", type: "boolean", notes: "Default: false" },
            { name: "available_for_rent", type: "boolean", notes: "Default: false" },
            { name: "available_for_swap", type: "boolean", notes: "Default: false" },
            { name: "sale_price", type: "decimal" },
            { name: "sale_price_negotiable", type: "boolean", notes: "Default: false" },
            { name: "original_price", type: "decimal" },
            { name: "currency", type: "string", notes: "Default: USD" },
            { name: "rental_price_hourly", type: "decimal" },
            { name: "rental_price_daily", type: "decimal" },
            { name: "rental_price_weekly", type: "decimal" },
            { name: "rental_price_monthly", type: "decimal" },
            { name: "rental_deposit", type: "decimal" },
            { name: "min_rental_duration", type: "integer", notes: "In hours" },
            { name: "max_rental_duration", type: "integer", notes: "In hours" },
            { name: "swap_preferences", type: "text" },
            { name: "swap_categories", type: "json", notes: "Array of category IDs" },
            { name: "swap_estimated_value", type: "decimal" },
            { name: "quantity", type: "integer", notes: "Default: 1" },
            { name: "quantity_available", type: "integer", notes: "Default: 1" },
            { name: "is_unlimited", type: "boolean", notes: "Default: false" },
            { name: "weight", type: "decimal" },
            { name: "weight_unit", type: "string", notes: "Default: kg" },
            { name: "dimensions", type: "json", notes: "{length, width, height, unit}" },
            { name: "location_country", type: "string" },
            { name: "location_city", type: "string" },
            { name: "location_area", type: "string" },
            { name: "latitude", type: "decimal" },
            { name: "longitude", type: "decimal" },
            { name: "offers_shipping", type: "boolean", notes: "Default: true" },
            { name: "shipping_cost", type: "decimal" },
            { name: "free_shipping", type: "boolean", notes: "Default: false" },
            { name: "pickup_available", type: "boolean", notes: "Default: true" },
            { name: "attributes", type: "json", notes: "Dynamic category attributes" },
            { name: "tags", type: "json", notes: "Array of tags" },
            { name: "views_count", type: "integer", notes: "Default: 0, Read-only" },
            { name: "favorites_count", type: "integer", notes: "Default: 0, Read-only" },
            { name: "inquiries_count", type: "integer", notes: "Default: 0, Read-only" },
            { name: "is_approved", type: "boolean", notes: "Default: false" },
            { name: "approved_at", type: "timestamp" },
            { name: "approved_by", type: "uuid", relationship: "directus_users" },
            { name: "rejection_reason", type: "text" },
            { name: "published_at", type: "timestamp" },
            { name: "expires_at", type: "timestamp" },
            { name: "images", type: "O2M", relationship: "product_images" },
            { name: "videos", type: "O2M", relationship: "product_videos" },
            { name: "favorites", type: "O2M", relationship: "product_favorites" },
            { name: "offers_received", type: "O2M", relationship: "offers" },
            { name: "reviews", type: "O2M", relationship: "reviews" },
            { name: "seo", type: "O2O", relationship: "seo_metadata" },
          ],
        },
        {
          id: "product_images",
          name: "product_images",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "image", type: "uuid", relationship: "directus_files", notes: "Required" },
            { name: "sort", type: "integer", notes: "Default: 0, Sortable" },
            { name: "is_primary", type: "boolean", notes: "Default: false" },
            { name: "alt_text", type: "string" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "product_videos",
          name: "product_videos",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "video", type: "uuid", relationship: "directus_files", notes: "Optional" },
            { name: "video_url", type: "string", notes: "External URL (YouTube)" },
            { name: "thumbnail", type: "uuid", relationship: "directus_files" },
            { name: "sort", type: "integer", notes: "Default: 0, Sortable" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "product_favorites",
          name: "product_favorites",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
      ],
    },
    {
      id: "offers",
      name: "Offers & Negotiations",
      icon: HandshakeIcon,
      color: "#ec4899",
      collections: [
        {
          id: "offers",
          name: "offers",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            {
              name: "status",
              type: "string",
              notes: "pending, accepted, declined, countered, expired, cancelled, completed",
            },
            { name: "offer_type", type: "string", notes: "Required: purchase, rental, swap" },
            { name: "buyer_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "seller_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "quantity", type: "integer", notes: "Default: 1" },
            { name: "offered_price", type: "decimal" },
            { name: "original_price", type: "decimal" },
            { name: "rental_start_date", type: "timestamp" },
            { name: "rental_end_date", type: "timestamp" },
            { name: "rental_duration_type", type: "string", notes: "hourly, daily, weekly, monthly" },
            { name: "rental_duration", type: "integer" },
            { name: "rental_total_price", type: "decimal" },
            { name: "rental_deposit_amount", type: "decimal" },
            { name: "swap_cash_difference", type: "decimal" },
            { name: "swap_cash_direction", type: "string", notes: "buyer_pays, seller_pays, none" },
            { name: "message", type: "text" },
            { name: "is_counter_offer", type: "boolean", notes: "Default: false" },
            { name: "parent_offer_id", type: "uuid", relationship: "offers", notes: "Self-referential" },
            { name: "counter_price", type: "decimal" },
            { name: "counter_message", type: "text" },
            { name: "preferred_delivery_method", type: "string", notes: "shipping, pickup, both" },
            { name: "preferred_meeting_location", type: "text" },
            { name: "preferred_meeting_time", type: "timestamp" },
            { name: "expires_at", type: "timestamp" },
            { name: "responded_at", type: "timestamp" },
            { name: "response_message", type: "text" },
            { name: "swap_items", type: "O2M", relationship: "swap_offer_items" },
            { name: "messages", type: "O2M", relationship: "offer_messages" },
            { name: "counter_offers", type: "O2M", relationship: "offers" },
            { name: "order", type: "O2O", relationship: "orders" },
          ],
        },
        {
          id: "swap_offer_items",
          name: "swap_offer_items",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "offer_id", type: "uuid", relationship: "offers", notes: "Required" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "estimated_value", type: "decimal" },
            { name: "condition_at_offer", type: "string", notes: "new, like_new, good, fair, poor" },
            { name: "notes", type: "text" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "offer_messages",
          name: "offer_messages",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "offer_id", type: "uuid", relationship: "offers", notes: "Required" },
            { name: "sender_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "message", type: "text", notes: "Required" },
            { name: "attachments", type: "json" },
            { name: "is_read", type: "boolean", notes: "Default: false" },
            { name: "read_at", type: "timestamp" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
      ],
    },
    {
      id: "orders",
      name: "Orders & Transactions",
      icon: ShoppingCart,
      color: "#06b6d4",
      collections: [
        {
          id: "orders",
          name: "orders",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            {
              name: "status",
              type: "string",
              notes:
                "pending, confirmed, processing, shipped, delivered, completed, cancelled, refunded, disputed, active, returned, overdue",
            },
            { name: "order_type", type: "string", notes: "Required: purchase, rental, swap" },
            { name: "order_number", type: "string", notes: "Required, Unique" },
            { name: "buyer_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "seller_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "store_id", type: "uuid", relationship: "stores", notes: "Optional" },
            { name: "offer_id", type: "uuid", relationship: "offers", notes: "Optional" },
            { name: "subtotal", type: "decimal", notes: "Required" },
            { name: "discount_amount", type: "decimal", notes: "Default: 0" },
            { name: "shipping_cost", type: "decimal", notes: "Default: 0" },
            { name: "tax_amount", type: "decimal", notes: "Default: 0" },
            { name: "total_amount", type: "decimal", notes: "Required" },
            { name: "currency", type: "string", notes: "Default: USD" },
            { name: "rental_start_date", type: "timestamp" },
            { name: "rental_end_date", type: "timestamp" },
            { name: "rental_deposit", type: "decimal" },
            { name: "deposit_status", type: "string", notes: "pending, held, released, forfeited" },
            { name: "actual_return_date", type: "timestamp" },
            { name: "late_fee", type: "decimal" },
            { name: "shipping_address", type: "json" },
            { name: "billing_address", type: "json" },
            { name: "delivery_method", type: "string", notes: "shipping, pickup" },
            { name: "pickup_location", type: "json" },
            { name: "estimated_delivery_date", type: "date" },
            { name: "actual_delivery_date", type: "timestamp" },
            { name: "tracking_number", type: "string" },
            { name: "shipping_carrier", type: "string" },
            { name: "tracking_url", type: "string" },
            { name: "buyer_notes", type: "text" },
            { name: "seller_notes", type: "text" },
            { name: "internal_notes", type: "text", notes: "Admin only" },
            { name: "cancelled_at", type: "timestamp" },
            { name: "cancelled_by", type: "uuid", relationship: "directus_users" },
            { name: "cancellation_reason", type: "text" },
            { name: "confirmed_at", type: "timestamp" },
            { name: "shipped_at", type: "timestamp" },
            { name: "delivered_at", type: "timestamp" },
            { name: "completed_at", type: "timestamp" },
            { name: "items", type: "O2M", relationship: "order_items" },
            { name: "payments", type: "O2M", relationship: "payments" },
            { name: "reviews", type: "O2M", relationship: "reviews" },
          ],
        },
        {
          id: "order_items",
          name: "order_items",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "order_id", type: "uuid", relationship: "orders", notes: "Required" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "product_title", type: "string", notes: "Required (Snapshot)" },
            { name: "product_image", type: "string", notes: "Snapshot URL" },
            { name: "product_attributes", type: "json", notes: "Snapshot" },
            { name: "quantity", type: "integer", notes: "Default: 1" },
            { name: "unit_price", type: "decimal", notes: "Required" },
            { name: "total_price", type: "decimal", notes: "Required" },
            { name: "rental_rate", type: "decimal" },
            { name: "rental_rate_type", type: "string", notes: "hourly, daily, weekly, monthly" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "swap_transactions",
          name: "swap_transactions",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            {
              name: "status",
              type: "string",
              notes: "pending, both_confirmed, in_progress, completed, cancelled, disputed",
            },
            { name: "transaction_number", type: "string", notes: "Required, Unique" },
            { name: "offer_id", type: "uuid", relationship: "offers" },
            { name: "party_a_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "party_b_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "cash_difference", type: "decimal", notes: "Default: 0" },
            { name: "cash_payer_id", type: "uuid", relationship: "directus_users" },
            { name: "cash_payment_status", type: "string", notes: "pending, paid, confirmed" },
            { name: "exchange_method", type: "string", notes: "in_person, shipping" },
            { name: "meeting_location", type: "json" },
            { name: "meeting_datetime", type: "timestamp" },
            { name: "party_a_confirmed", type: "boolean", notes: "Default: false" },
            { name: "party_a_confirmed_at", type: "timestamp" },
            { name: "party_b_confirmed", type: "boolean", notes: "Default: false" },
            { name: "party_b_confirmed_at", type: "timestamp" },
            { name: "party_a_received", type: "boolean", notes: "Default: false" },
            { name: "party_a_received_at", type: "timestamp" },
            { name: "party_b_received", type: "boolean", notes: "Default: false" },
            { name: "party_b_received_at", type: "timestamp" },
            { name: "notes", type: "text" },
            { name: "completed_at", type: "timestamp" },
            { name: "cancelled_at", type: "timestamp" },
            { name: "items", type: "O2M", relationship: "swap_transaction_items" },
            { name: "payments", type: "O2M", relationship: "payments" },
            { name: "reviews", type: "O2M", relationship: "reviews" },
          ],
        },
        {
          id: "swap_transaction_items",
          name: "swap_transaction_items",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "swap_transaction_id", type: "uuid", relationship: "swap_transactions", notes: "Required" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Required" },
            { name: "owner_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "estimated_value", type: "decimal" },
            { name: "tracking_number", type: "string" },
            { name: "shipping_carrier", type: "string" },
            { name: "shipped_at", type: "timestamp" },
            { name: "delivered_at", type: "timestamp" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "payments",
          name: "payments",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "pending, processing, completed, failed, refunded" },
            { name: "payment_number", type: "string", notes: "Required, Unique" },
            { name: "order_id", type: "uuid", relationship: "orders", notes: "Optional" },
            { name: "swap_transaction_id", type: "uuid", relationship: "swap_transactions", notes: "Optional" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "amount", type: "decimal", notes: "Required" },
            { name: "currency", type: "string", notes: "Default: USD" },
            { name: "payment_method", type: "string", notes: "credit_card, debit_card, bank_transfer, wallet, cash" },
            { name: "payment_gateway", type: "string", notes: "stripe, paypal, etc." },
            { name: "gateway_transaction_id", type: "string" },
            { name: "gateway_response", type: "json" },
            { name: "processing_fee", type: "decimal", notes: "Default: 0" },
            { name: "platform_fee", type: "decimal", notes: "Default: 0" },
            { name: "refunded_amount", type: "decimal", notes: "Default: 0" },
            { name: "refund_reason", type: "text" },
            { name: "refunded_at", type: "timestamp" },
            { name: "completed_at", type: "timestamp" },
          ],
        },
      ],
    },
    {
      id: "communication",
      name: "Communication",
      icon: MessageSquare,
      color: "#6366f1",
      collections: [
        {
          id: "conversations",
          name: "conversations",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "active, archived, blocked" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Optional" },
            { name: "offer_id", type: "uuid", relationship: "offers", notes: "Optional" },
            { name: "order_id", type: "uuid", relationship: "orders", notes: "Optional" },
            { name: "last_message_at", type: "timestamp" },
            { name: "last_message_preview", type: "text" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
            { name: "participants", type: "O2M", relationship: "conversation_participants" },
            { name: "messages", type: "O2M", relationship: "messages" },
          ],
        },
        {
          id: "conversation_participants",
          name: "conversation_participants",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "conversation_id", type: "uuid", relationship: "conversations", notes: "Required" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "last_read_at", type: "timestamp" },
            { name: "unread_count", type: "integer", notes: "Default: 0" },
            { name: "is_muted", type: "boolean", notes: "Default: false" },
            { name: "is_archived", type: "boolean", notes: "Default: false" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "messages",
          name: "messages",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "conversation_id", type: "uuid", relationship: "conversations", notes: "Required" },
            { name: "sender_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "message_type", type: "string", notes: "text, image, file, offer, system" },
            { name: "content", type: "text" },
            { name: "attachments", type: "json" },
            { name: "offer_id", type: "uuid", relationship: "offers", notes: "Optional" },
            { name: "is_read", type: "boolean", notes: "Default: false" },
            { name: "read_at", type: "timestamp" },
            { name: "is_deleted", type: "boolean", notes: "Default: false" },
            { name: "deleted_at", type: "timestamp" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "notifications",
          name: "notifications",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "notification_type", type: "string", notes: "offer_received, offer_accepted, order_placed, etc." },
            { name: "category", type: "string", notes: "offers, orders, rentals, swaps, messages, reviews, system" },
            { name: "title", type: "string", notes: "Required" },
            { name: "message", type: "text", notes: "Required" },
            { name: "reference_type", type: "string", notes: "product, order, offer, etc." },
            { name: "reference_id", type: "uuid" },
            { name: "action_url", type: "string" },
            { name: "image", type: "string" },
            { name: "is_read", type: "boolean", notes: "Default: false" },
            { name: "read_at", type: "timestamp" },
            { name: "sent_via_email", type: "boolean", notes: "Default: false" },
            { name: "sent_via_push", type: "boolean", notes: "Default: false" },
            { name: "sent_via_sms", type: "boolean", notes: "Default: false" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
      ],
    },
    {
      id: "reviews",
      name: "Reviews",
      icon: Star,
      color: "#eab308",
      collections: [
        {
          id: "reviews",
          name: "reviews",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "pending, published, hidden, flagged" },
            { name: "review_type", type: "string", notes: "Required: product, user, store, transaction" },
            { name: "reviewer_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "product_id", type: "uuid", relationship: "products", notes: "Optional" },
            { name: "reviewed_user_id", type: "uuid", relationship: "directus_users", notes: "Optional" },
            { name: "store_id", type: "uuid", relationship: "stores", notes: "Optional" },
            { name: "order_id", type: "uuid", relationship: "orders", notes: "Optional" },
            { name: "swap_transaction_id", type: "uuid", relationship: "swap_transactions", notes: "Optional" },
            { name: "overall_rating", type: "integer", notes: "Required, 1-5" },
            { name: "communication_rating", type: "integer", notes: "1-5" },
            { name: "accuracy_rating", type: "integer", notes: "1-5" },
            { name: "shipping_rating", type: "integer", notes: "1-5" },
            { name: "value_rating", type: "integer", notes: "1-5" },
            { name: "title", type: "string" },
            { name: "content", type: "text" },
            { name: "pros", type: "text" },
            { name: "cons", type: "text" },
            { name: "images", type: "json" },
            { name: "is_verified_purchase", type: "boolean", notes: "Default: false" },
            { name: "helpful_count", type: "integer", notes: "Default: 0" },
            { name: "not_helpful_count", type: "integer", notes: "Default: 0" },
            { name: "response", type: "text", notes: "Seller response" },
            { name: "response_date", type: "timestamp" },
            { name: "votes", type: "O2M", relationship: "review_votes" },
          ],
        },
        {
          id: "review_votes",
          name: "review_votes",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "review_id", type: "uuid", relationship: "reviews", notes: "Required" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "is_helpful", type: "boolean", notes: "Required" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
          ],
        },
      ],
    },
    {
      id: "other",
      name: "Other",
      icon: Settings,
      color: "#64748b",
      collections: [
        {
          id: "promotions",
          name: "promotions",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, active, paused, expired" },
            { name: "name", type: "string", notes: "Required" },
            { name: "code", type: "string", notes: "Unique" },
            { name: "description", type: "text" },
            { name: "promotion_type", type: "string", notes: "percentage, fixed_amount, free_shipping, buy_x_get_y" },
            { name: "discount_value", type: "decimal" },
            { name: "minimum_purchase", type: "decimal" },
            { name: "maximum_discount", type: "decimal" },
            { name: "usage_limit", type: "integer" },
            { name: "usage_count", type: "integer", notes: "Default: 0" },
            { name: "per_user_limit", type: "integer", notes: "Default: 1" },
            { name: "applies_to", type: "string", notes: "all, categories, products, stores, users" },
            { name: "applicable_ids", type: "json" },
            { name: "valid_from", type: "timestamp" },
            { name: "valid_until", type: "timestamp" },
          ],
        },
        {
          id: "reports",
          name: "reports",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "pending, reviewing, resolved, dismissed" },
            { name: "reporter_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "entity_type", type: "string", notes: "Required: product, user, store, review, message" },
            { name: "entity_id", type: "uuid", notes: "Required" },
            {
              name: "reason",
              type: "string",
              notes: "Required: spam, inappropriate, counterfeit, scam, harassment, other",
            },
            { name: "description", type: "text" },
            { name: "evidence", type: "json" },
            { name: "resolved_at", type: "timestamp" },
            { name: "resolved_by", type: "uuid", relationship: "directus_users" },
            { name: "resolution_notes", type: "text" },
            {
              name: "action_taken",
              type: "string",
              notes: "warning, content_removed, user_suspended, user_banned, no_action",
            },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "saved_searches",
          name: "saved_searches",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "user_id", type: "uuid", relationship: "directus_users", notes: "Required" },
            { name: "name", type: "string" },
            { name: "search_query", type: "text" },
            { name: "filters", type: "json" },
            { name: "notify_new_matches", type: "boolean", notes: "Default: false" },
            { name: "notification_frequency", type: "string", notes: "instant, daily, weekly" },
            { name: "last_notified_at", type: "timestamp" },
            { name: "date_created", type: "timestamp", notes: "Auto" },
            { name: "date_updated", type: "timestamp", notes: "Auto" },
          ],
        },
        {
          id: "seo_metadata",
          name: "seo_metadata",
          fields: [
            { name: "id", type: "uuid", isPrimaryKey: true, notes: "Primary Key" },
            { name: "status", type: "string", notes: "draft, published" },
            { name: "collection_name", type: "string", notes: "Required (e.g., products, categories)" },
            { name: "item_id", type: "uuid", notes: "Required" },
            { name: "meta_title", type: "string", notes: "Max 60 chars" },
            { name: "meta_title_ar", type: "string", notes: "Arabic" },
            { name: "meta_description", type: "text", notes: "Max 160 chars" },
            { name: "meta_description_ar", type: "text", notes: "Arabic" },
            { name: "meta_keywords", type: "json", notes: "Array of keywords" },
            { name: "meta_keywords_ar", type: "json", notes: "Arabic keywords" },
            { name: "canonical_url", type: "string" },
            { name: "og_title", type: "string", notes: "Open Graph" },
            { name: "og_description", type: "text", notes: "Open Graph" },
            { name: "og_image", type: "uuid", relationship: "directus_files", notes: "Open Graph" },
            { name: "og_type", type: "string", notes: "website, article, product" },
            { name: "twitter_card", type: "string", notes: "summary, summary_large_image" },
            { name: "twitter_title", type: "string" },
            { name: "twitter_description", type: "text" },
            { name: "twitter_image", type: "uuid", relationship: "directus_files" },
            { name: "structured_data", type: "json", notes: "JSON-LD schema" },
            { name: "robots", type: "string", notes: "index, noindex, follow, nofollow" },
            { name: "priority", type: "decimal", notes: "Sitemap priority 0.0-1.0" },
            {
              name: "change_frequency",
              type: "string",
              notes: "always, hourly, daily, weekly, monthly, yearly, never",
            },
          ],
        },
      ],
    },
  ],
}
